"""add task description

Revision ID: e117336a51e5
Revises: 0001_create_tasks
Create Date: 2026-04-19 20:15:50.273730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e117336a51e5'
down_revision: Union[str, None] = '0001_create_tasks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
